# Generated by Django 4.2.16 on 2024-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
